/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day05

fun main() {
    var input = object {}::class.java.getResource("/input").readText()

    val split = input.split("\n\n")

    val stacks = split[0].replace("[", "").replace("]", "")//.replace("   ", "0")
    val rows = split[0].split("\n").map { it.chunked(4) }.dropLast(1)
    val amountOfStacks = stacks.split("\n").last().trim().split(" ").last { it.isNotEmpty() }.toInt()
    val columns = mutableListOf<MutableList<String>>()

    for (i in 0 until amountOfStacks) {
        columns.add(rows.map { it.get(i).replace("[", "").replace("]", "").trim() }.filter { it.isNotEmpty() }.toMutableList())
    }

    val instructions = split[1].split("\n").map { Regex("\\d+").findAll(it).map { f -> f.value }.joinToString("|") }

    println(columns)

    instructions.forEach {
        val split = it.split("|")
        val amount = split[0].toInt()
        val from = split[1].toInt() - 1
        val to = split[2].toInt() - 1

        val toBeMoved = columns[from].take(amount) // get amount
        columns[from] = columns[from].drop(amount).toMutableList() // drop the amount from the list

        toBeMoved.forEach {
            columns[to].add(0, it)
        }
    }

    println("after")
    println(columns)
    println("stacks: $amountOfStacks")
    println(instructions)

    var result = ""

    columns.forEach {
        result += it.first()
    }

    println("result: $result")

//    instructions.forEach {
//        val split = it.split("|")
//        val amount = split[0].toInt()
//        val from = split[1].toInt() - 1
//        val to = split[2].toInt() - 1
//
//        val toBeMoved = columns[from].take(amount) // get amount
//        columns[from] = columns[from].drop(amount).toMutableList() // drop the amount from the list
//
//        columns[to].addAll(0, toBeMoved)
//    }
//    result = ""
//
//    columns.forEach {
//        result += it.first()
//    }
//    println("result2: $result")
}
