/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day03

import kotlin.math.absoluteValue

fun main() {
    var input = object {}::class.java.getResource("/input").readText()


    var rucksacks = input
            .split("\n")
            .map {
                it.substring(0, it.length / 2) to it.substring(it.length / 2)
            }

    var priority = rucksacks.map { // find shared items
        it.first.filter { c: Char ->
            it.second.contains(c)
        }
    }
            .map {
                it.first()
            }.sumOf {
                var additionalValue = if (it.isUpperCase()) 27 else 1
                var a = (it.lowercaseChar().code - 97) + additionalValue
                // println("$it ($a)")
                a
            }


    var badgePriority = rucksacks
            .map { it.first+it.second }
            .chunked(3)
            .map {
                it.first().first { c: Char ->
                    it.all {r ->
                        r.contains(c)
                    }
                } to it
            }
            .map {
                println(it)
                it
            }.map {
                it.first to (it.first.code - 65).absoluteValue
            }.map {
                println(it)
                it.first
            }.sumOf {
                var additionalValue = if (it.isUpperCase()) 27 else 1
                var a = (it.lowercaseChar().code - 97) + additionalValue
                // println("$it ($a)")
                a
            }



    println(priority)
    println(badgePriority)
}
