/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day04

fun main() {
    var input = object {}::class.java.getResource("/input").readText()

    var groups = input.split("\n").map {
        val pair = it.split(",")
        pair.first() to pair[1]
    }.map {
        var first = it.first.split("-").map { id ->
            id.toInt()
        }
        var second = it.second.split("-").map { id ->
            id.toInt()
        }
        first[0]..first[1] to second[0]..second[1]
    }

    var part1 = groups.filter {
        (it.first.contains(it.second.first) && it.first.contains(it.second.last))
                || (it.second.contains(it.first.first) && it.second.contains(it.first.last))
    }

    var part2 = groups.filter {
        (it.first.contains(it.second.first) || it.first.contains(it.second.last))
                || (it.second.contains(it.first.first) || it.second.contains(it.first.last))
    }

    println(part1.count())
    println(part2.count())
}
